### ISSUE TITLE
Spams Log File, please remove, or move to debug only output mode switch.

### ISSUE THREAD

**Issue by FlexibleGames** [Wip-Sama/yafla#1]
https://github.com/Wip-Sama/yafla/blob/c3f795635c238b8931a08d61544cc19ed6d2c861/scripts/experimental/gui_builder.lua#L97

**Comment by Wip-Sama** [comment]
Ho I forgot to remove this, Ill remove thsi and add a debug flag somewhere to avoid this happening again
